[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Dummy"
version = "1.0"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "src"
